openapi: 3.0.0
info:
  title: AWS-Test
  description: API Docs for AWS-Test server
  version: 0.0.1
servers:
  - url: https://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: https://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /test:
    get:
      summary: Returns a JSON containing a message.
      responses:
        200:
          description: "Success"
          schema:
            type: object
            properties:
              message:
                type: string