openapi: 3.0.0
info:
  title: AWS-Test
  description: API Docs for AWS-Test server
  version: 0.0.1
servers:
  - url: https://18.222.161.136:5000
  - url: https:localhost:5000
  - url: /
paths:
  /test:
    get:
      summary: Returns a JSON containing a message.
      responses:
        200:
          description: "Success"
          schema:
            type: object
            properties:
              message:
                type: string